### PR TITLE
Aesthetic looks improvements

### PR DESCRIPTION
**Pull request by CedzzAcharon**
I added some unique features to our stopwatch GUI for it to become more aesthetic than to stick to simple interface. What I'm proud of my improvements to our stopwatch GUI is when we click the start, resume, pause, and reset button. You can copy and paste to VS code for you to run and see what surprises I added to our stopwatch GUI. If there's an issue, feel free to discuss, we can surely fix it in no time.

### CODE REVIEW

**Review by AlzynJosselCellero — COMMENTED** [review]
I can see that you put something that will improve our stopwatch and i can say is... Nicely Done. You make it aesthetic that make it popular. Thank you for your ideas to improve it.

**Review by AlzynJosselCellero — COMMENTED** [review]
It's good that you give improvements to our stopwatch. However, the code wont run, but we can identify what causes it and sure it would run perfectly after

**Comment by CedzzAcharon** [comment]
> It's good that you give improvements to our stopwatch. However, the code wont run, but we can identify what causes it and sure it would run perfectly after

okay, just what I expected.

**Review by AlzynJosselCellero — COMMENTED** [review]
also in the reset function the set label back to zero. It's okay that the b.place_forget() only. You can remove the resume_button to reset_button.

**Comment by CedzzAcharon** [comment]
> also in the reset function the set label back to zero. It's okay that the b.place_forget() only. You can remove the resume_button to reset_button.

I'll try to fix it right away. Thanks for identifying the issues in my changes

**Review by AlzynJosselCellero — COMMENTED** [review]
I apologize. The code you make that will improve our stopwatch is okay. I apologize again.

**Comment by CedzzAcharon** [comment]
> I apologize. The code you make that will improve our stopwatch is okay. I apologize again.

That's good to hear that my code changes works

**Review by AlzynJosselCellero — COMMENTED** [review]
I will merge it now

**Pull request merged**
